  AWSTemplateFormatVersion: '2010-09-09'
  Transform: AWS::Serverless-2016-10-31
  Description: AWS Serverless Quarkus HTTP - org.tjpower
  Globals:
    Api:
      EndpointConfiguration: REGIONAL
      BinaryMediaTypes:
        - "*/*"

  Resources:
    KotlinLambdaFunction:
      Type: AWS::Serverless::Function
      Properties:
        Handler: io.quarkus.amazon.lambda.runtime.QuarkusStreamHandler::handleRequest
        Runtime: java11
        CodeUri: target/kotlin-lambda-1.0-SNAPSHOT-runner.jar
        MemorySize: 256
        Timeout: 15
        Policies: AWSLambdaBasicExecutionRole
        Tracing: Active
